### Data Analysis:

* Data --- Raw input(consisting of impurities)
* Information --- processed data
* Getting the required information by removing unwanted data is called Data Analysis
* For this DataAnalysis we will use 5 libraries:
    * Numpy -- scientific Calculations
    * Pandas -- numerical data as well as the string.Cleaning of data 
    * Scikit Learn -- Machine learning library
    * Matplotlib -- graphical representation
    * Seaborn -- advanced than the matplotlib
* Steps involved in Data Analysis:
    * gathering data
    * cleaning of the data
    * fill those null values or remove those nulls
    * Graphical representation
    * Feeding the data to the ML algorithm
    * Deploy the algorithm to the Machine

### Numpy :

* Numpy --- Numerical Python.
* This is used to perfrom scientific calculations and mathematical operations.
* Numpy library creates all the output in the array format
* We can perform matrix operations using this numpy library.
* The arrays gives us the high efficiency when compared to lists.
* we can create different dimensional arrays using numpy.
*  1 to 32 dimensional arrays can be created using numpy library.
* **Comparision between the numpy array and list:**
    * Array occupies very less space when compared to lists.
    * we cannot perform complex operations on lists where as in arrays we can.
    * Execution time is also very less when compared to lists.
    * vector operations can be performed using arrays.
    * Data can be created in different dimensions.



In [5]:
## 1-D arrays
import numpy as np

# by using list
li = [1,2,3,4,5]
al =np.array(li)

In [7]:
print(al)
print(type(al))
print(li)
print(type(li))

[1 2 3 4 5]
<class 'numpy.ndarray'>
[1, 2, 3, 4, 5]
<class 'list'>


In [10]:
# by using tuple
t = (5,6,7,8,9)
at = np.array(t)

print(at)
print(type(at))
print(type(t))

[5 6 7 8 9]
<class 'numpy.ndarray'>
<class 'tuple'>


In [14]:
at.ndim # number of dimensions

1

In [15]:
at.shape # no of rows and columns

(5,)

In [16]:
at.itemsize # each element size in the memory

4

In [17]:
at.size # total number of elements

5

In [22]:
## 2D arrays
li = [[1,2,3],[4,5,6]]

a2 = np.array(li)
print(a2)
print(a2.shape)

print(a2.size)

print(a2.ndim)

[[1 2 3]
 [4 5 6]]
(2, 3)
6
2


In [ ]:
# by using tuple create 2D array

In [24]:
li = [[[1,2,3]]]
a3 = np.array(li)
print(a3.ndim)
print(a3)

3
[[[1 2 3]]]


In [26]:
# range(start,stop,step) ==> s1=0,s2=given,s3=1
# arange(start,stop,step) ==>

b = np.arange(1,11,2)
print(b)
print(type(b))

[1 3 5 7 9]
<class 'numpy.ndarray'>


In [29]:
# 10 numbers b/w 1 to 11
c = np.linspace(1,11,20)
print(c)

[ 1.          1.52631579  2.05263158  2.57894737  3.10526316  3.63157895
  4.15789474  4.68421053  5.21052632  5.73684211  6.26315789  6.78947368
  7.31578947  7.84210526  8.36842105  8.89473684  9.42105263  9.94736842
 10.47368421 11.        ]


In [33]:
d = np.logspace(1,11,20)
print(d)

[1.00000000e+01 3.35981829e+01 1.12883789e+02 3.79269019e+02
 1.27427499e+03 4.28133240e+03 1.43844989e+04 4.83293024e+04
 1.62377674e+05 5.45559478e+05 1.83298071e+06 6.15848211e+06
 2.06913808e+07 6.95192796e+07 2.33572147e+08 7.84759970e+08
 2.63665090e+09 8.85866790e+09 2.97635144e+10 1.00000000e+11]


## Accessing array elements

In [36]:
a = np.arange(1,10)
print(a)

[1 2 3 4 5 6 7 8 9]


In [37]:
a[3]

4

In [39]:
a[-3]

7

In [40]:
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [41]:
# to get alternative elements
a[::2]

array([1, 3, 5, 7, 9])

In [42]:
# 2 4 6 8
a[1::2]

array([2, 4, 6, 8])

In [44]:
## 2D array elements
# reshape(new_shape) --> to convert the shape of an array
b = a.reshape(3,3)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [49]:
b[0]

array([1, 2, 3])

In [50]:
b[2]

array([7, 8, 9])

In [60]:
print(b[1,1])
print(b[:,1])# 2 5 8

5
[2 5 8]


array([7, 8, 9])

In [61]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [63]:
# 5 6 8 9
b[1:,1:]

array([[5, 6],
       [8, 9]])

In [65]:
# 1 2
# 4 5
b[:2,:2]

array([[1, 2],
       [4, 5]])

In [66]:
b[1,1] = 100
print(b)

[[  1   2   3]
 [  4 100   6]
 [  7   8   9]]


In [77]:
## 3D Arrays
n = np.arange(1,17)
print(n)

b = n.reshape(4,4)
#print(b)

c = n.reshape(4,4,1) # first_para =no of 2d arrays ,
print(c)             # second_para = no of rows in each 2d array
print(c.ndim)                     # third_para = no of columns in each 2d array

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
3


In [78]:
d = n.reshape(2,4,2) # 2D-2, rows = 4 columns = 2
print(d)

[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]]


In [79]:
e = n.reshape(2,1,8)
print(e)

[[[ 1  2  3  4  5  6  7  8]]

 [[ 9 10 11 12 13 14 15 16]]]


In [80]:
d

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12],
        [13, 14],
        [15, 16]]])

In [83]:
d[0]

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [84]:
# 11
d[1,1,0]

11

In [85]:
d[1,1:3,1] # 

array([12, 14])

In [87]:
# 5 7 13 15
d[:,2:,0]

array([[ 5,  7],
       [13, 15]])

In [95]:
p = np.array([1,2,3,4],ndmin = 13)
type(p)
p.ndim

13

In [96]:
p.shape

(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 4)

In [97]:
a

array([  1,   2,   3,   4, 100,   6,   7,   8,   9])

In [100]:
a.min()
a.max()

100

In [103]:
np.average(a)

15.555555555555555

In [104]:
np.mean(a)

15.555555555555555

In [105]:
np.median(a)

6.0

In [108]:
np.var(a)

898.0246913580246

In [110]:
np.std(a)

29.96706010535609

In [111]:
np.argmin(a) # index value of min value

0

In [112]:
a.min()

1

In [113]:
np.sum(a)

140

In [114]:
a = np.array([1,2,3,4,5,6,7,8])
# cumulative sum of a ==> [1,3,5..]
np.cumsum(a)

array([ 1,  3,  6, 10, 15, 21, 28, 36], dtype=int32)

In [115]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [116]:
b.min()

1

In [117]:
b.max()

16

In [118]:
np.mean(b)

8.5

In [119]:
np.median(b)

8.5

In [120]:
np.cumsum(b)

array([  1,   3,   6,  10,  15,  21,  28,  36,  45,  55,  66,  78,  91,
       105, 120, 136], dtype=int32)

In [122]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [121]:
np.min(b,axis=0) # axis = 0 column  axis=1 row

array([1, 2, 3, 4])

In [123]:
np.max(b,axis=1)

array([ 4,  8, 12, 16])

In [124]:
np.mean(b,axis=0)

array([ 7.,  8.,  9., 10.])

In [125]:
np.cumsum(b,axis=1)

array([[ 1,  3,  6, 10],
       [ 5, 11, 18, 26],
       [ 9, 19, 30, 42],
       [13, 27, 42, 58]], dtype=int32)

## Stacking --> Arranging elements

- vstack --> vertical arranging
- hstack --> horizontal arranging

In [126]:
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [128]:
al

array([1, 2, 3, 4, 5])

In [138]:
ah = np.hstack(a)
print(ah.shape)
ah

(8,)


array([1, 2, 3, 4, 5, 6, 7, 8])

In [137]:
av = np.vstack(a)
print(av.shape)
av

(8, 1)


array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [139]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [143]:
np.hstack(b)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [144]:
np.hstack((a,al))

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5])

In [148]:
np.vstack((b,[10,20,30,40],[[1,2,3,4],[6,7,8,9]]))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [10, 20, 30, 40],
       [ 1,  2,  3,  4],
       [ 6,  7,  8,  9]])

In [ ]:
## Copy the arrays
# ravel() --> modifications are done in orginal also
# flatten() -->

In [164]:
org = np.array([1,2,3,4,5,6])
org

array([1, 2, 3, 4, 5, 6])

In [165]:
ravel = org.ravel()
print(ravel)

[1 2 3 4 5 6]


In [166]:
flatten = org.flatten()
flatten

array([1, 2, 3, 4, 5, 6])

In [168]:
ravel[2] = 12 

In [169]:
print(ravel)
print(org)

[ 1  2 12  4  5  6]
[ 1  2 12  4  5  6]


In [170]:
flatten

array([1, 2, 3, 4, 5, 6])

In [171]:
flatten[3] = 15
print(flatten)
print(org)

[ 1  2  3 15  5  6]
[ 1  2 12  4  5  6]


In [173]:
b2

array([[1, 2, 3],
       [4, 5, 6]])

In [174]:
np.sqrt(b2)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [176]:
np.remainder(b2,3)

array([[1, 2, 0],
       [1, 2, 0]], dtype=int32)

In [177]:
np.power(b2,3)

array([[  1,   8,  27],
       [ 64, 125, 216]], dtype=int32)

In [179]:
np.multiply(b2,6)

array([[ 6, 12, 18],
       [24, 30, 36]])

In [180]:
np.divide(b2,3)

array([[0.33333333, 0.66666667, 1.        ],
       [1.33333333, 1.66666667, 2.        ]])

## Random methods

In [184]:
np.random.rand()  # it will generate a random number b/w 0 and 1

0.10763926772659382

In [191]:
np.random.randint(10)# start,stop,shape

4

In [195]:
np.random.randint(11,size = 8)# 1d array with 8 elements

array([4, 9, 1, 5, 8, 9, 6, 5])

In [200]:
np.random.randint(15,size=(7,6,4))

array([[[10,  3,  9,  4],
        [ 0, 11, 13,  6],
        [ 9,  9,  4, 13],
        [ 7,  1, 10,  7],
        [12,  7,  4,  0],
        [ 0, 14, 13,  3]],

       [[ 2,  2,  2,  7],
        [12,  6,  4,  7],
        [ 3,  3, 11,  8],
        [13,  2,  1,  2],
        [ 9,  2,  4,  1],
        [ 3,  1,  0,  6]],

       [[14, 11,  7,  9],
        [11,  3,  7,  7],
        [13,  6,  4,  9],
        [12,  7,  2, 14],
        [ 3,  4, 14, 11],
        [ 8, 12, 10,  5]],

       [[ 3,  3,  3,  4],
        [11, 12, 14,  6],
        [ 6,  0, 10, 14],
        [ 7, 11, 14, 12],
        [10,  5,  6,  0],
        [10,  2,  4,  1]],

       [[ 8,  0, 11,  9],
        [ 2,  5,  9,  6],
        [ 7, 11,  9,  5],
        [ 1, 12,  5, 10],
        [ 6, 14,  9,  2],
        [13,  7, 11,  2]],

       [[10,  2,  5, 10],
        [10,  9, 12, 13],
        [11,  8, 10,  0],
        [ 0,  2,  6,  7],
        [ 8,  1,  3,  1],
        [12, 14,  9,  4]],

       [[ 7, 14,  0,  1],
        [ 6,  9, 14,  5],


In [201]:
li = np.arange(1,10)
print(li)
np.random.shuffle(li)
print(li)

[1 2 3 4 5 6 7 8 9]
[4 7 8 1 6 9 2 5 3]


In [202]:
np.random.choice(range(1,20),10)

array([ 4,  6, 19, 14, 11, 18,  7,  3, 18, 11])

In [210]:
np.random.choice(range(1,30),(5,3))

array([[23, 21, 29],
       [10, 10,  1],
       [ 8, 17,  2],
       [ 6,  7,  9],
       [ 8,  7, 16]])

In [208]:
np.random.choice(range(1,30),(2,3,2,2))

array([[[[ 5,  8],
         [ 7, 10]],

        [[10,  6],
         [26,  2]],

        [[10, 12],
         [16, 15]]],


       [[[ 8, 16],
         [15, 27]],

        [[13, 27],
         [27, 24]],

        [[ 2,  9],
         [ 4, 25]]]])