### Numpy

#### Filtering

In [2]:
l = [10,20,30,40,50,60]
for i in l:
    if i>30:
        print(i)

40
50
60


In [3]:
[i for i in l if i>30]

[40, 50, 60]

In [4]:
import numpy as np

In [5]:
arr = np.array([10,20,30,40,50,60])
arr

array([10, 20, 30, 40, 50, 60])

In [6]:
arr>30

array([False, False, False,  True,  True,  True])

In [7]:
arr[arr>30]

array([40, 50, 60])

In [8]:
x = np.arange(50,100)
x

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [9]:
x%2==0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False])

In [12]:
x[x%2==0]

array([50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82,
       84, 86, 88, 90, 92, 94, 96, 98])

In [17]:
x[(x>60)&(x<90)]

array([61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89])

In [20]:
x[(x>60) & (x<90) &(x%2==0)]


array([62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88])

In [21]:
x[((x>60)&(x<90))&(x%2==0)]


array([62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88])

|---- or
!---- not

## Pandas

- Data Analysis and Data Manipulation
- It is in the format of table(rows,columns)
- Import / Export the data 

##### 2 types:

 - Series - 1d array - list,tuple,array
 
     - data types - float,int,string/object
 
 - DataFrame - 2d array - list,tuple,dict,array
 
     - data types - float,int,string/object
 

In [24]:
import pandas as pd

In [25]:
# pip install pandas

In [28]:
a = pd.Series([1,2,3,4,7.8,"apssdc"])
a

0         1
1         2
2         3
3         4
4       7.8
5    apssdc
dtype: object

In [31]:
b = pd.Series((1,2,3,4,7.8))
b

0    1.0
1    2.0
2    3.0
3    4.0
4    7.8
dtype: float64

In [34]:
b = pd.Series((1,2,3,4,7.8),index=["a","b","c","d","e"])
b

a    1.0
b    2.0
c    3.0
d    4.0
e    7.8
dtype: float64

In [35]:
b.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [36]:
a.index

RangeIndex(start=0, stop=6, step=1)

In [37]:
b

a    1.0
b    2.0
c    3.0
d    4.0
e    7.8
dtype: float64

In [38]:
b["e"]

7.8

In [39]:
pd.DataFrame([1,2,3,4])

0
0  1
1  2
2  3
3  4

In [40]:
d = pd.DataFrame([["apssdc",14,7],["ml",15,7]])
d

0   1  2
0  apssdc  14  7
1      ml  15  7

In [41]:
d = pd.Series([["apssdc",14,7],["ml",15,7]])
d

0    [apssdc, 14, 7]
1        [ml, 15, 7]
dtype: object

In [43]:
d = pd.DataFrame([["apssdc",14,7],["ml",15,7]],columns =("name","date","month") 
                 ,index = ["a","b"])
d

name  date  month
a  apssdc    14      7
b      ml    15      7

In [ ]:
{key:values}

In [48]:
d1 = pd.DataFrame({"a":[1,2,3],"b":[4,5,6]},index = [1,2,3])
d1

a  b
1  1  4
2  2  5
3  3  6

In [49]:
d1.index

Int64Index([1, 2, 3], dtype='int64')

In [50]:
d1.columns

Index(['a', 'b'], dtype='object')

In [51]:
d1.shape

(3, 2)

In [52]:
# Accessing the elements

In [53]:
d

name  date  month
a  apssdc    14      7
b      ml    15      7

In [54]:
d.shape

(2, 3)

In [56]:
d["name"]

a    apssdc
b        ml
Name: name, dtype: object

In [62]:
d.name

a    apssdc
b        ml
Name: name, dtype: object

In [57]:
d["month"]

a    7
b    7
Name: month, dtype: int64

In [61]:
d[["month","name","date"]]


month    name  date
a      7  apssdc    14
b      7      ml    15

In [65]:
d1[["a","b"]]

a  b
1  1  4
2  2  5
3  3  6

In [66]:
d

name  date  month
a  apssdc    14      7
b      ml    15      7

In [70]:
d["date"]["b"]

15

In [71]:
d1

a  b
1  1  4
2  2  5
3  3  6

In [72]:
d1["a"][2]

2

In [80]:
d1[-1:]

a  b
3  3  6

In [81]:
d1[0:1]

a  b
1  1  4

- Load datasets

In [82]:
data = pd.read_csv("market.csv")


In [83]:
data


Ord_id  Prod_id   Ship_id    Cust_id       Sales  Discount  \
0     Ord_5446  Prod_16  SHP_7609  Cust_1818    136.8100      0.01   
1     Ord_5406  Prod_13  SHP_7549  Cust_1818     42.2700      0.01   
2     Ord_5446   Prod_4  SHP_7610  Cust_1818   4701.6900      0.00   
3     Ord_5456   Prod_6  SHP_7625  Cust_1818   2337.8900      0.09   
4     Ord_5485  Prod_17  SHP_7664  Cust_1818   4233.1500      0.08   
5     Ord_5446   Prod_6  SHP_7608  Cust_1818    164.0200      0.03   
6       Ord_31  Prod_12    SHP_41    Cust_26     14.7600      0.01   
7     Ord_4725   Prod_4  SHP_6593  Cust_1641   3410.1575      0.10   
8     Ord_4725  Prod_13  SHP_6593  Cust_1641    162.0000      0.01   
9     Ord_4725   Prod_6  SHP_6593  Cust_1641     57.2200      0.07   
10    Ord_4743   Prod_2  SHP_6615  Cust_1641   4072.0100      0.01   
11    Ord_1925   Prod_6  SHP_2637   Cust_708    465.9000      0.05   
12    Ord_2978  Prod_16  SHP_4112  Cust_1088    305.0500      0.04   
13    Ord_2207  Prod_11  SHP_3093   Cust_839   3364.2480      0.10   
14    Ord_2207  Prod_10  SHP_3006   Cust_839   1410.9300      0.08   
15    Ord_2280   Prod_5  SHP_3114   Cust_839    460.6900      0.06   
16    Ord_2282   Prod_9  SHP_3122   Cust_839    443.4600      0.06   
17    Ord_4471  Prod_15  SHP_6228  Cust_1521  13255.9300      0.02   
18    Ord_4427   Prod_6  SHP_6171  Cust_1521    283.1300      0.08   
19     Ord_996  Prod_13  SHP_1378   Cust_371     41.9700      0.05   
20     Ord_996  Prod_13  SHP_1378   Cust_371     57.1700      0.08   
21     Ord_996   Prod_6  SHP_1378   Cust_371     81.2500      0.01   
22     Ord_996   Prod_5  SHP_1377   Cust_371   3202.2500      0.09   
23     Ord_996   Prod_7  SHP_1378   Cust_371     35.6400      0.05   
24    Ord_2573   Prod_3  SHP_3525   Cust_931    197.6100      0.08   
25    Ord_2335  Prod_13  SHP_3204   Cust_931     38.2600      0.03   
26    Ord_2456   Prod_5  SHP_3367   Cust_931    109.5800      0.00   
27    Ord_2405   Prod_9  SHP_3300   Cust_931   1062.6900      0.01   
28    Ord_2573   Prod_4  SHP_3527   Cust_931   3594.7435      0.05   
29    Ord_2478  Prod_12  SHP_3395   Cust_931    139.9800      0.07   
...        ...      ...       ...        ...         ...       ...   
8369  Ord_3633   Prod_3  SHP_5031  Cust_1274   1169.2600      0.02   
8370  Ord_2696  Prod_13  SHP_3690  Cust_1006     62.7800      0.04   
8371  Ord_2624   Prod_4  SHP_3591  Cust_1006   4924.1350      0.07   
8372  Ord_2772   Prod_9  SHP_3806  Cust_1006     56.9000      0.03   
8373  Ord_2600  Prod_16  SHP_3560  Cust_1006    106.6400      0.10   
8374  Ord_2658   Prod_5  SHP_3637  Cust_1006   1082.6600      0.08   
8375  Ord_2772   Prod_3  SHP_3806  Cust_1006   1413.8200      0.10   
8376  Ord_2624   Prod_8  SHP_3590  Cust_1006   1211.0000      0.00   
8377  Ord_2722  Prod_12  SHP_3729  Cust_1006     34.0100      0.00   
8378  Ord_2706   Prod_2  SHP_3705  Cust_1006   1361.9100      0.05   
8379  Ord_2722   Prod_5  SHP_3730  Cust_1006   1008.9500      0.04   
8380  Ord_2772   Prod_6  SHP_3807  Cust_1006    308.9200      0.04   
8381  Ord_2696   Prod_4  SHP_3691  Cust_1006   2836.0505      0.01   
8382  Ord_2658   Prod_3  SHP_3636  Cust_1006    120.9800      0.00   
8383  Ord_2722   Prod_1  SHP_3731  Cust_1006   3508.3300      0.04   
8384  Ord_4620   Prod_3  SHP_6435  Cust_1577     59.6200      0.04   
8385  Ord_1833   Prod_3  SHP_2527   Cust_637    611.1600      0.04   
8386  Ord_2324   Prod_7  SHP_3189   Cust_851    121.8700      0.07   
8387  Ord_2220   Prod_3  SHP_3019   Cust_851     41.0600      0.04   
8388  Ord_4424   Prod_1  SHP_6165  Cust_1519    994.0400      0.03   
8389  Ord_4444  Prod_13  SHP_6192  Cust_1519    159.4100      0.00   
8390  Ord_5435  Prod_16  SHP_7594  Cust_1798    316.9900      0.04   
8391  Ord_5435   Prod_4  SHP_7594  Cust_1798   1991.8985      0.07   
8392  Ord_5384   Prod_9  SHP_7519  Cust_1798    181.5000      0.08   
8393  Ord_5348   Prod_8  SHP_7470  Cust_1798    356.7200      0.07   
8394  Ord_5353   P

In [84]:
data.columns

Index(['Ord_id', 'Prod_id', 'Ship_id', 'Cust_id', 'Sales', 'Discount',
       'Order_Quantity', 'Profit', 'Shipping_Cost', 'Product_Base_Margin'],
      dtype='object')

In [85]:
data.shape

(8399, 10)

In [86]:
data.head()

Ord_id  Prod_id   Ship_id    Cust_id    Sales  Discount  Order_Quantity  \
0  Ord_5446  Prod_16  SHP_7609  Cust_1818   136.81      0.01              23   
1  Ord_5406  Prod_13  SHP_7549  Cust_1818    42.27      0.01              13   
2  Ord_5446   Prod_4  SHP_7610  Cust_1818  4701.69      0.00              26   
3  Ord_5456   Prod_6  SHP_7625  Cust_1818  2337.89      0.09              43   
4  Ord_5485  Prod_17  SHP_7664  Cust_1818  4233.15      0.08              35   

    Profit  Shipping_Cost  Product_Base_Margin  
0   -30.51           3.60                 0.56  
1     4.56           0.93                 0.54  
2  1148.90           2.50                 0.59  
3   729.34          14.30                 0.37  
4  1219.87          26.30                 0.38

In [87]:
data.index

RangeIndex(start=0, stop=8399, step=1)

In [88]:
data.head(10)

Ord_id  Prod_id   Ship_id    Cust_id      Sales  Discount  \
0  Ord_5446  Prod_16  SHP_7609  Cust_1818   136.8100      0.01   
1  Ord_5406  Prod_13  SHP_7549  Cust_1818    42.2700      0.01   
2  Ord_5446   Prod_4  SHP_7610  Cust_1818  4701.6900      0.00   
3  Ord_5456   Prod_6  SHP_7625  Cust_1818  2337.8900      0.09   
4  Ord_5485  Prod_17  SHP_7664  Cust_1818  4233.1500      0.08   
5  Ord_5446   Prod_6  SHP_7608  Cust_1818   164.0200      0.03   
6    Ord_31  Prod_12    SHP_41    Cust_26    14.7600      0.01   
7  Ord_4725   Prod_4  SHP_6593  Cust_1641  3410.1575      0.10   
8  Ord_4725  Prod_13  SHP_6593  Cust_1641   162.0000      0.01   
9  Ord_4725   Prod_6  SHP_6593  Cust_1641    57.2200      0.07   

   Order_Quantity   Profit  Shipping_Cost  Product_Base_Margin  
0              23   -30.51           3.60                 0.56  
1              13     4.56           0.93                 0.54  
2              26  1148.90           2.50                 0.59  
3              43   729.34          14.30                 0.37  
4              35  1219.87          26.30                 0.38  
5              23   -47.64           6.15                 0.37  
6               5     1.32           0.50                 0.36  
7              48  1137.91           0.99                 0.55  
8              33    45.84           0.71                 0.52  
9               8   -27.72           6.60                 0.37

In [89]:
data.tail()

Ord_id  Prod_id   Ship_id    Cust_id      Sales  Discount  \
8394  Ord_5353   Prod_4  SHP_7479  Cust_1798  2841.4395      0.08   
8395  Ord_5411   Prod_6  SHP_7555  Cust_1798   127.1600      0.10   
8396  Ord_5388   Prod_6  SHP_7524  Cust_1798   243.0500      0.02   
8397  Ord_5348  Prod_15  SHP_7469  Cust_1798  3872.8700      0.03   
8398  Ord_5459   Prod_6  SHP_7628  Cust_1798   603.6900      0.00   

      Order_Quantity  Profit  Shipping_Cost  Product_Base_Margin  
8394              28  374.63           7.69                 0.59  
8395              20  -74.03           6.92                 0.37  
8396              39  -70.85           5.35                 0.40  
8397              23  565.34          30.00                 0.62  
8398              47  131.39           4.86                 0.38

In [90]:
data.tail(2)

Ord_id  Prod_id   Ship_id    Cust_id    Sales  Discount  \
8397  Ord_5348  Prod_15  SHP_7469  Cust_1798  3872.87      0.03   
8398  Ord_5459   Prod_6  SHP_7628  Cust_1798   603.69      0.00   

      Order_Quantity  Profit  Shipping_Cost  Product_Base_Margin  
8397              23  565.34          30.00                 0.62  
8398              47  131.39           4.86                 0.38

In [93]:
data.sample(3)

Ord_id Prod_id   Ship_id    Cust_id    Sales  Discount  \
3351  Ord_2613  Prod_2  SHP_3575  Cust_1012  1757.43      0.02   
6594  Ord_2083  Prod_5  SHP_2847   Cust_793  3991.99      0.00   
3335   Ord_477  Prod_1   SHP_643   Cust_164   783.96      0.05   

      Order_Quantity   Profit  Shipping_Cost  Product_Base_Margin  
3351              40   490.77            3.5                 0.59  
6594              42 -1014.11           56.2                 0.74  
3335              38 -1195.29           35.0                 0.84

In [94]:
data.columns

Index(['Ord_id', 'Prod_id', 'Ship_id', 'Cust_id', 'Sales', 'Discount',
       'Order_Quantity', 'Profit', 'Shipping_Cost', 'Product_Base_Margin'],
      dtype='object')

In [95]:
data.index

RangeIndex(start=0, stop=8399, step=1)

In [96]:
data.shape

(8399, 10)

In [97]:
# statistical analysis

In [98]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8399 entries, 0 to 8398
Data columns (total 10 columns):
Ord_id                 8399 non-null object
Prod_id                8399 non-null object
Ship_id                8399 non-null object
Cust_id                8399 non-null object
Sales                  8399 non-null float64
Discount               8399 non-null float64
Order_Quantity         8399 non-null int64
Profit                 8399 non-null float64
Shipping_Cost          8399 non-null float64
Product_Base_Margin    8336 non-null float64
dtypes: float64(5), int64(1), object(4)
memory usage: 656.2+ KB


In [99]:
8399-8336

63

In [100]:
data.describe()

Sales     Discount  Order_Quantity        Profit  Shipping_Cost  \
count   8399.000000  8399.000000     8399.000000   8399.000000    8399.000000   
mean    1775.878179     0.049671       25.571735    181.184424      12.838557   
std     3585.050525     0.031823       14.481071   1196.653371      17.264052   
min        2.240000     0.000000        1.000000 -14140.700000       0.490000   
25%      143.195000     0.020000       13.000000    -83.315000       3.300000   
50%      449.420000     0.050000       26.000000     -1.500000       6.070000   
75%     1709.320000     0.080000       38.000000    162.750000      13.990000   
max    89061.050000     0.250000       50.000000  27220.690000     164.730000   

       Product_Base_Margin  
count          8336.000000  
mean              0.512513  
std               0.135589  
min               0.350000  
25%               0.380000  
50%               0.520000  
75%               0.590000  
max               0.850000

In [102]:
data.isnull().sum()

Ord_id                  0
Prod_id                 0
Ship_id                 0
Cust_id                 0
Sales                   0
Discount                0
Order_Quantity          0
Profit                  0
Shipping_Cost           0
Product_Base_Margin    63
dtype: int64

In [103]:
data.isnull().sum().sum()

63

In [104]:
# selecting rows

In [105]:
data[10:11]

Ord_id Prod_id   Ship_id    Cust_id    Sales  Discount  Order_Quantity  \
10  Ord_4743  Prod_2  SHP_6615  Cust_1641  4072.01      0.01              43   

     Profit  Shipping_Cost  Product_Base_Margin  
10  1675.98           0.99                 0.56

In [106]:
data[100:110]

Ord_id  Prod_id   Ship_id    Cust_id    Sales  Discount  \
100  Ord_1638   Prod_8  SHP_5892  Cust_1433   220.79      0.00   
101  Ord_1638   Prod_7  SHP_2261   Cust_565   201.14      0.08   
102  Ord_1557   Prod_2  SHP_2152   Cust_565  1736.53      0.10   
103   Ord_209  Prod_13   SHP_285    Cust_45    30.51      0.09   
104   Ord_246   Prod_8   SHP_341    Cust_45   862.20      0.10   
105   Ord_122  Prod_17   SHP_165    Cust_45    42.31      0.06   
106   Ord_121   Prod_8   SHP_164    Cust_45  1143.45      0.06   
107   Ord_250  Prod_15   SHP_346    Cust_45  8901.78      0.04   
108   Ord_122   Prod_3   SHP_166    Cust_45   152.67      0.04   
109   Ord_139  Prod_17   SHP_186    Cust_45  2671.21      0.06   

     Order_Quantity   Profit  Shipping_Cost  Product_Base_Margin  
100               7   -91.51           4.00                 0.74  
101              37   -51.25           3.37                 0.54  
102              46   457.03           3.99                 0.56  
103              11   -17.68           2.40                 0.58  
104              29   -45.10           4.00                 0.75  
105               2   -53.08           8.51                 0.40  
106              31   304.42           1.99                 0.51  
107              31  2795.36          24.49                  NaN  
108              11    12.76           4.98                 0.40  
109              14   636.18          15.59                 0.36

In [107]:
data[100:120:3]

Ord_id  Prod_id   Ship_id    Cust_id      Sales  Discount  \
100  Ord_1638   Prod_8  SHP_5892  Cust_1433   220.7900      0.00   
103   Ord_209  Prod_13   SHP_285    Cust_45    30.5100      0.09   
106   Ord_121   Prod_8   SHP_164    Cust_45  1143.4500      0.06   
109   Ord_139  Prod_17   SHP_186    Cust_45  2671.2100      0.06   
112   Ord_209   Prod_1   SHP_286    Cust_45   127.8000      0.07   
115    Ord_23  Prod_12    SHP_31    Cust_18   282.0700      0.03   
118  Ord_5351   Prod_4  SHP_7474  Cust_1800  1463.0965      0.00   

     Order_Quantity  Profit  Shipping_Cost  Product_Base_Margin  
100               7  -91.51           4.00                 0.74  
103              11  -17.68           2.40                 0.58  
106              31  304.42           1.99                 0.51  
109              14  636.18          15.59                 0.36  
112               8  -30.48           7.51                 0.57  
115              39  140.01           0.49                 0.38  
118              14  162.67           2.50                 0.57

In [108]:
# selecting the columns

In [110]:
data["Ship_id"].head()

0    SHP_7609
1    SHP_7549
2    SHP_7610
3    SHP_7625
4    SHP_7664
Name: Ship_id, dtype: object

In [112]:
data[["Ship_id","Cust_id","Sales"]].head()

Ship_id    Cust_id    Sales
0  SHP_7609  Cust_1818   136.81
1  SHP_7549  Cust_1818    42.27
2  SHP_7610  Cust_1818  4701.69
3  SHP_7625  Cust_1818  2337.89
4  SHP_7664  Cust_1818  4233.15

In [113]:
# iloc and loc

# iloc --> position based index
# loc ---> label based index

In [114]:
data.iloc[100]

Ord_id                  Ord_1638
Prod_id                   Prod_8
Ship_id                 SHP_5892
Cust_id                Cust_1433
Sales                     220.79
Discount                       0
Order_Quantity                 7
Profit                    -91.51
Shipping_Cost                  4
Product_Base_Margin         0.74
Name: 100, dtype: object

In [116]:
data[100:101]

Ord_id Prod_id   Ship_id    Cust_id   Sales  Discount  Order_Quantity  \
100  Ord_1638  Prod_8  SHP_5892  Cust_1433  220.79       0.0               7   

     Profit  Shipping_Cost  Product_Base_Margin  
100  -91.51            4.0                 0.74

In [117]:
data.iloc[100:200]

Ord_id  Prod_id   Ship_id    Cust_id       Sales  Discount  \
100  Ord_1638   Prod_8  SHP_5892  Cust_1433    220.7900      0.00   
101  Ord_1638   Prod_7  SHP_2261   Cust_565    201.1400      0.08   
102  Ord_1557   Prod_2  SHP_2152   Cust_565   1736.5300      0.10   
103   Ord_209  Prod_13   SHP_285    Cust_45     30.5100      0.09   
104   Ord_246   Prod_8   SHP_341    Cust_45    862.2000      0.10   
105   Ord_122  Prod_17   SHP_165    Cust_45     42.3100      0.06   
106   Ord_121   Prod_8   SHP_164    Cust_45   1143.4500      0.06   
107   Ord_250  Prod_15   SHP_346    Cust_45   8901.7800      0.04   
108   Ord_122   Prod_3   SHP_166    Cust_45    152.6700      0.04   
109   Ord_139  Prod_17   SHP_186    Cust_45   2671.2100      0.06   
110   Ord_239   Prod_4   SHP_332    Cust_45   2157.3085      0.00   
111   Ord_250   Prod_2   SHP_345    Cust_45    324.5500      0.08   
112   Ord_209   Prod_1   SHP_286    Cust_45    127.8000      0.07   
113   Ord_135   Prod_9   SHP_182    Cust_45     30.8300      0.04   
114    Ord_60  Prod_12    SHP_81    Cust_45    176.2600      0.07   
115    Ord_23  Prod_12    SHP_31    Cust_18    282.0700      0.03   
116    Ord_23   Prod_4    SHP_31    Cust_18    426.0370      0.01   
117  Ord_5374   Prod_8  SHP_7504  Cust_1800   1222.5900      0.02   
118  Ord_5351   Prod_4  SHP_7474  Cust_1800   1463.0965      0.00   
119  Ord_5417  Prod_12  SHP_7565  Cust_1800    128.1300      0.09   
120  Ord_5354   Prod_5  SHP_7480  Cust_1800    152.4400      0.08   
121  Ord_5423  Prod_17  SHP_7577  Cust_1800  13070.2000      0.07   
122  Ord_5351   Prod_6  SHP_7475  Cust_1800    246.3000      0.02   
123  Ord_2340   Prod_5  SHP_3210   Cust_933    136.6100      0.01   
124  Ord_2432   Prod_4  SHP_3339   Cust_933   3883.4715      0.10   
125  Ord_2480   Prod_3  SHP_3397   Cust_933    169.6100      0.10   
126  Ord_2394  Prod_13  SHP_3284   Cust_933     64.3600      0.06   
127  Ord_2372  Prod_10  SHP_3256   Cust_933   1764.9700      0.07   
128  Ord_2566  Prod_13  SHP_3515   Cust_933    422.2500      0.06   
129  Ord_2340  Prod_11  SHP_3211   Cust_933   2907.6300      0.04   
..        ...      ...       ...        ...         ...       ...   
170  Ord_2973   Prod_4  SHP_4102  Cust_1480   6264.1855      0.01   
171  Ord_2973   Prod_9  SHP_6073  Cust_1480   5410.9500      0.09   
172  Ord_4572   Prod_6  SHP_6360  Cust_1480    377.8300      0.06   
173  Ord_1995   Prod_6  SHP_2724   Cust_702    240.1400      0.06   
174  Ord_1915   Prod_6  SHP_2623   Cust_702    980.9500      0.02   
175  Ord_2273   Prod_5  SHP_3101  Cust_1104    180.4300      0.02   
176  Ord_2273   Prod_8  SHP_3101   Cust_878   2899.9800      0.10   
177  Ord_2273   Prod_6  SHP_3102   Cust_878    233.3800      0.10   
178  Ord_2246   Prod_2  SHP_3054   Cust_878    294.5200      0.09   
179  Ord_2273   Prod_4  SHP_3100   Cust_878   1077.8085      0.06   
180  Ord_5153  Prod_13  SHP_7201  Cust_1753    176.5000      0.01   
181  Ord_5153   Prod_1  SHP_7201  Cust_1753   1546.8000      0.07   
182  Ord_5239  Prod_13  SHP_7318  Cust_1753    452.2800      0.09   
183  Ord_5157  Prod_15  SHP_7208  Cust_1753   5149.0600      0.03   
184  Ord_5230   Prod_4  SHP_7304  Cust_1753   2197.4115      0.00   
185  Ord_5153  Prod_11  SHP_7202  Cust_1753   3457.5600      0.02   
186  Ord_5159   Prod_5  SHP_7210  Cust_1753   2213.9200      0.03   
187  Ord_5230   Prod_1  SHP_7304  Cust_1753    423.0400      0.05   
188  Ord_5239  Prod_13  SHP_7318  Cust_1753     55.8200      0.01   
189  Ord_2831   Prod_3  SHP_3893  Cust_1036  18092.6600      0.09   
190  Ord_2791  Prod_12  SHP_3837  Cust_1036     68.5400      0.10   
191  Ord_2791  Prod_11  SHP_3838  Cust_1036  10351.0100      0.08   
192  Ord_2739   Prod_5  SHP_3758  Cust_1036    363.9200      0.00   
193  Ord_2585  Prod_11  SHP_3540   Cust_997   7287.5500      0.04   
194  Ord_2653   Prod_6  SHP_3630   Cust_997    306.3000      0.07   
195  Ord_2691   Prod_5  SHP_3685   Cust_997    311.1900      0.03   
196  

In [119]:
data.iloc[[2,10,45,1000,3000,4]]

Ord_id  Prod_id   Ship_id    Cust_id    Sales  Discount  \
2     Ord_5446   Prod_4  SHP_7610  Cust_1818  4701.69      0.00   
10    Ord_4743   Prod_2  SHP_6615  Cust_1641  4072.01      0.01   
45    Ord_4768  Prod_12  SHP_6650  Cust_1579     3.85      0.08   
1000  Ord_1895   Prod_4  SHP_2601   Cust_686  2433.55      0.05   
3000  Ord_5342   Prod_3  SHP_7459  Cust_1771   242.46      0.02   
4     Ord_5485  Prod_17  SHP_7664  Cust_1818  4233.15      0.08   

      Order_Quantity   Profit  Shipping_Cost  Product_Base_Margin  
2                 26  1148.90           2.50                 0.59  
10                43  1675.98           0.99                 0.56  
45                 1    -1.36           0.99                 0.37  
1000              23   355.93           8.08                 0.57  
3000              44     9.30           2.99                 0.38  
4                 35  1219.87          26.30                 0.38

In [120]:
data.iloc[3:10,4:]

Sales  Discount  Order_Quantity   Profit  Shipping_Cost  \
3  2337.8900      0.09              43   729.34          14.30   
4  4233.1500      0.08              35  1219.87          26.30   
5   164.0200      0.03              23   -47.64           6.15   
6    14.7600      0.01               5     1.32           0.50   
7  3410.1575      0.10              48  1137.91           0.99   
8   162.0000      0.01              33    45.84           0.71   
9    57.2200      0.07               8   -27.72           6.60   

   Product_Base_Margin  
3                 0.37  
4                 0.38  
5                 0.37  
6                 0.36  
7                 0.55  
8                 0.52  
9                 0.37

In [122]:
data.loc[4,"Sales"]

4233.15

In [123]:
data.loc[9,"Order_Quantity"]

8

In [125]:
data["Order_Quantity"].head()

0    23
1    13
2    26
3    43
4    35
Name: Order_Quantity, dtype: int64

In [126]:
# Filtering

In [128]:
data.head()

Ord_id  Prod_id   Ship_id    Cust_id    Sales  Discount  Order_Quantity  \
0  Ord_5446  Prod_16  SHP_7609  Cust_1818   136.81      0.01              23   
1  Ord_5406  Prod_13  SHP_7549  Cust_1818    42.27      0.01              13   
2  Ord_5446   Prod_4  SHP_7610  Cust_1818  4701.69      0.00              26   
3  Ord_5456   Prod_6  SHP_7625  Cust_1818  2337.89      0.09              43   
4  Ord_5485  Prod_17  SHP_7664  Cust_1818  4233.15      0.08              35   

    Profit  Shipping_Cost  Product_Base_Margin  
0   -30.51           3.60                 0.56  
1     4.56           0.93                 0.54  
2  1148.90           2.50                 0.59  
3   729.34          14.30                 0.37  
4  1219.87          26.30                 0.38

In [131]:
data[(data["Sales"]>4000) & (data["Profit"]>4000)]

Ord_id  Prod_id   Ship_id    Cust_id     Sales  Discount  \
17    Ord_4471  Prod_15  SHP_6228  Cust_1521  13255.93      0.02   
133   Ord_2432   Prod_3  SHP_3338   Cust_933  15337.58      0.10   
165   Ord_4702   Prod_3  SHP_6560  Cust_1603  11823.52      0.10   
189   Ord_2831   Prod_3  SHP_3893  Cust_1036  18092.66      0.09   
197   Ord_2753   Prod_3  SHP_3778   Cust_997  23106.46      0.08   
385   Ord_3707  Prod_17  SHP_5136  Cust_1307  28359.40      0.05   
535   Ord_4857  Prod_17  SHP_6777   Cust_227  19100.45      0.00   
699   Ord_2839  Prod_17  SHP_3905  Cust_1048  14383.83      0.01   
734   Ord_4705  Prod_17  SHP_6566  Cust_1592  21320.58      0.09   
755   Ord_1026  Prod_17  SHP_1417   Cust_363  15602.93      0.00   
808   Ord_4322  Prod_17  SHP_6027  Cust_1440  15152.55      0.05   
954   Ord_1989  Prod_10  SHP_2718   Cust_750  19269.05      0.00   
1184  Ord_5181  Prod_17  SHP_7238  Cust_1750  23775.56      0.03   
1220   Ord_283  Prod_17   SHP_383    Cust_85  10051.52      0.05   
1252  Ord_1536  Prod_14  SHP_2125   Cust_561  14475.74      0.06   
1265  Ord_5250  Prod_17  SHP_7331  Cust_1769  24105.87      0.07   
1324   Ord_214  Prod_17   SHP_297    Cust_82  15251.50      0.06   
1448  Ord_2673   Prod_1  SHP_3661  Cust_1027  21337.27      0.02   
1471   Ord_893  Prod_17  SHP_1228   Cust_315  18028.07      0.02   
1494   Ord_188  Prod_14   SHP_253    Cust_97  17387.65      0.08   
1576  Ord_5416   Prod_3  SHP_7562  Cust_1812  14410.78      0.02   
1681   Ord_809  Prod_17  SHP_1113   Cust_266  18775.76      0.03   
1740  Ord_3667  Prod_17  SHP_5082  Cust_1291  21532.26      0.09   
1787  Ord_2872  Prod_14  SHP_7219  Cust_1748  21555.60      0.02   
1792  Ord_5148  Prod_14  SHP_7194  Cust_1748  19224.92      0.10   
1848  Ord_5315  Prod_14  SHP_7423  Cust_1780  21141.07      0.06   
2013  Ord_4305  Prod_14  SHP_6008  Cust_1436  17599.39      0.03   
2216  Ord_4216  Prod_14  SHP_5881  Cust_1432  26126.92      0.04   
2253  Ord_3143  Prod_14  SHP_4362  Cust_1170  28664.52      0.09   
2259  Ord_1978  Prod_17  SHP_2703   Cust_725  25312.00      0.01   
...        ...      ...       ...        ...       ...       ...   
6218  Ord_1764   Prod_3  SHP_2445   Cust_578  18697.24      0.02   
6252  Ord_4757  Prod_15  SHP_6633  Cust_1604  16451.33      0.01   
6323  Ord_3581   Prod_1  SHP_4958  Cust_1264  17853.64      0.02   
6384  Ord_4473  Prod_17  SHP_6232  Cust_1535  20265.22      0.08   
6484  Ord_3627  Prod_17  SHP_5022  Cust_1281  24559.91      0.01   
6494  Ord_1293  Prod_17  SHP_1784   Cust_483  17717.34      0.00   
6653  Ord_5391  Prod_14  SHP_7527  Cust_1799  24233.54      0.07   
6660  Ord_5425  Prod_14  SHP_7580  Cust_1799  27720.98      0.07   
6705   Ord_706   Prod_2   SHP_966   Cust_242  16002.29      0.09   
6758   Ord_128  Prod_17   SHP_174    Cust_87  16066.85      0.07   
6759  Ord_2163  Prod_15  SHP_2947   Cust_815  15963.09      0.03   
6765  Ord_5186  Prod_17  SHP_7247  Cust_1763  26095.13      0.03   
6797  Ord_1265  Prod_14  SHP_1749   Cust_466  24051.49      0.07   
6855  Ord_4336  Prod_17  SHP_6043  Cust_1461  15260.78      0.07   
6926  Ord_2171  Prod_15  SHP_2958   Cust_800  23239.96      0.06   
6979  Ord_3236  Prod_10  SHP_4488  Cust_1194  21062.91      0.01   
7006  Ord_5361   Prod_3  SHP_7489  Cust_1793  21752.01      0.03   
7015  Ord_1151   Prod_3  SHP_1585   Cust_442  15383.70      0.03   
7091   Ord_911  Prod_10  SHP_1255   Cust_302  28180.08      0.02   
7286  Ord_1767  Prod_14  SHP_2450   Cust_583  16743.76      0.00   
7547  Ord_3170  Prod_10  SHP_4400  Cust_1162  29345.27      0.03   
7592  Ord_3229  Prod_17  SHP_4479  Cust_1195  16172.44      0.03   
7638  Ord_4953   Prod_3  SHP_6911  Cust_1692  10094.43      0.03   
7706    Ord_79  Prod_17   SHP_105    Cust_42  22079.47      0.06   
7964  Ord_1686  Prod_15  SHP_2331   Cust_581  19342.84      0.01   
8042  Ord_5357  Prod_11  SHP_7483  Cust_1803  14451.75      0.01   
8078  Ord_5368  Prod_14  SHP_7497  Cust_1795  17279.62      0.04

### Data Preprocessing using scikit-Learn

- Problems:
    - insufficient of data
    - outliers
    - missing data
    - too much of data
    - duplicate data
- Scaling techniques
    - Standarad scalar
    - Robust scalar
    - Mix-Max scalar/range scalar

In [134]:
from sklearn import preprocessing

In [135]:
print(dir(preprocessing))

['Binarizer', 'CategoricalEncoder', 'FunctionTransformer', 'Imputer', 'KBinsDiscretizer', 'KernelCenterer', 'LabelBinarizer', 'LabelEncoder', 'MaxAbsScaler', 'MinMaxScaler', 'MultiLabelBinarizer', 'Normalizer', 'OneHotEncoder', 'OrdinalEncoder', 'PolynomialFeatures', 'PowerTransformer', 'QuantileTransformer', 'RobustScaler', 'StandardScaler', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_discretization', '_encoders', '_function_transformer', 'add_dummy_feature', 'base', 'binarize', 'data', 'imputation', 'label', 'label_binarize', 'maxabs_scale', 'minmax_scale', 'normalize', 'power_transform', 'quantile_transform', 'robust_scale', 'scale']


In [136]:
print(help(preprocessing.minmax_scale))

Help on function minmax_scale in module sklearn.preprocessing.data:

minmax_scale(X, feature_range=(0, 1), axis=0, copy=True)
    Transforms features by scaling each feature to a given range.
    
    This estimator scales and translates each feature individually such
    that it is in the given range on the training set, i.e. between
    zero and one.
    
    The transformation is given by (when ``axis=0``)::
    
        X_std = (X - X.min(axis=0)) / (X.max(axis=0) - X.min(axis=0))
        X_scaled = X_std * (max - min) + min
    
    where min, max = feature_range.
    
    The transformation is calculated as (when ``axis=0``)::
    
       X_scaled = scale * X + min - X.min(axis=0) * scale
       where scale = (max - min) / (X.max(axis=0) - X.min(axis=0))
    
    This transformation is often used as an alternative to zero mean,
    unit variance scaling.
    
    Read more in the :ref:`User Guide <preprocessing_scaler>`.
    
    .. versionadded:: 0.17
       *minmax_scale* funct

In [137]:
data.head()

Ord_id  Prod_id   Ship_id    Cust_id    Sales  Discount  Order_Quantity  \
0  Ord_5446  Prod_16  SHP_7609  Cust_1818   136.81      0.01              23   
1  Ord_5406  Prod_13  SHP_7549  Cust_1818    42.27      0.01              13   
2  Ord_5446   Prod_4  SHP_7610  Cust_1818  4701.69      0.00              26   
3  Ord_5456   Prod_6  SHP_7625  Cust_1818  2337.89      0.09              43   
4  Ord_5485  Prod_17  SHP_7664  Cust_1818  4233.15      0.08              35   

    Profit  Shipping_Cost  Product_Base_Margin  
0   -30.51           3.60                 0.56  
1     4.56           0.93                 0.54  
2  1148.90           2.50                 0.59  
3   729.34          14.30                 0.37  
4  1219.87          26.30                 0.38

In [138]:
data1 = data[["Sales","Discount","Order_Quantity","Profit","Shipping_Cost","Product_Base_Margin"]]

In [139]:
data1.head()

Sales  Discount  Order_Quantity   Profit  Shipping_Cost  \
0   136.81      0.01              23   -30.51           3.60   
1    42.27      0.01              13     4.56           0.93   
2  4701.69      0.00              26  1148.90           2.50   
3  2337.89      0.09              43   729.34          14.30   
4  4233.15      0.08              35  1219.87          26.30   

   Product_Base_Margin  
0                 0.56  
1                 0.54  
2                 0.59  
3                 0.37  
4                 0.38

In [140]:
sc = preprocessing.StandardScaler()

In [141]:
sc_t = sc.fit_transform(data1)

C:\Users\Alekhya\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:645: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
C:\Users\Alekhya\Anaconda3\lib\site-packages\sklearn\base.py:464: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)


In [142]:
sc_t

array([[-0.4572225 , -1.24669977, -0.17760343, -0.17691592, -0.53516446,
         0.35024724],
       [-0.48359469, -1.24669977, -0.86820119, -0.14760744, -0.68983029,
         0.20273374],
       [ 0.81616312, -1.56095642,  0.0295759 ,  0.8087331 , -0.59888446,
         0.5715175 ],
       ...,
       [-0.42758656, -0.93244313,  0.927353  , -0.2106286 , -0.43379172,
        -0.82986078],
       [ 0.58496154, -0.61818648, -0.17760343,  0.32104405,  0.99411568,
         0.79278775],
       [-0.32698506, -1.56095642,  1.47983121, -0.04161388, -0.46217609,
        -0.97737429]])

In [143]:
data1.columns

Index(['Sales', 'Discount', 'Order_Quantity', 'Profit', 'Shipping_Cost',
       'Product_Base_Margin'],
      dtype='object')

In [145]:
sc1_data = pd.DataFrame(sc_t,columns = data1.columns)
sc1_data.head()

Sales  Discount  Order_Quantity    Profit  Shipping_Cost  \
0 -0.457222 -1.246700       -0.177603 -0.176916      -0.535164   
1 -0.483595 -1.246700       -0.868201 -0.147607      -0.689830   
2  0.816163 -1.560956        0.029576  0.808733      -0.598884   
3  0.156775  1.267353        1.203592  0.458101       0.084657   
4  0.685463  0.953097        0.651114  0.868044       0.779785   

   Product_Base_Margin  
0             0.350247  
1             0.202734  
2             0.571517  
3            -1.051131  
4            -0.977374

#### Robust scaler

In [147]:
rs = preprocessing.RobustScaler()

In [148]:
rs_t = rs.fit_transform(data1)

In [149]:
rs_t

array([[-0.19960731, -0.66666667, -0.12      , -0.11789568, -0.23105706,
         0.19047619],
       [-0.25997286, -0.66666667, -0.52      ,  0.02462764, -0.4808232 ,
         0.0952381 ],
       [ 2.71515364, -0.83333333,  0.        ,  4.67518745, -0.33395697,
         0.33333333],
       ...,
       [-0.13177109, -0.5       ,  0.52      , -0.2818361 , -0.06735267,
        -0.57142857],
       [ 2.18593663, -0.33333333, -0.12      ,  2.30361896,  2.23854069,
         0.47619048],
       [ 0.09850427, -0.83333333,  0.84      ,  0.54006055, -0.1131899 ,
        -0.66666667]])

In [151]:
pd.DataFrame(rs_t,columns=data1.columns).head()

Sales  Discount  Order_Quantity    Profit  Shipping_Cost  \
0 -0.199607 -0.666667           -0.12 -0.117896      -0.231057   
1 -0.259973 -0.666667           -0.52  0.024628      -0.480823   
2  2.715154 -0.833333            0.00  4.675187      -0.333957   
3  1.205823  0.666667            0.68  2.970110       0.769878   
4  2.415982  0.500000            0.36  4.963607       1.892423   

   Product_Base_Margin  
0             0.190476  
1             0.095238  
2             0.333333  
3            -0.714286  
4            -0.666667